on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to productiom
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: | 
          cd ${{ secrets.WORK_DIR }}

          echo "Deploying application ..."

          # Enter maintenance mode
          php artisan down || true

          # Update codebase
          git fetch origin
          git reset --hard origin/main
          git pull origin release

          # Install dependencies based on lock file
          composer install --no-interaction --prefer-dist --optimize-autoloader

          # Clear cache
          php artisan config:cache
          php artisan optimize

          # Migrate database
          php artisan migrate --force

          # Exit maintenance mode
          php artisan up

          echo "Application deployed!"
